export type {
  Quest,
  DialogueNode,
  DialogueChoice,
  DialogueTree,
  Hotspot,
  Scene,
  Npc,
  Item,
  GameState,
  GameSettings,
  GameEnding,
  ItemId,
  SceneId,
  NpcId,
  QuestId,
  DialogueNodeId,
  InventoryState,
  QuestObjective,
} from './game';
export { DEFAULT_SETTINGS, ENDING_TITLES, INITIAL_SCENE, GAME_START_INTRO } from './game';
